-- Tabla: movimientos_generales_adjuntos
CREATE TABLE IF NOT EXISTS public.movimientos_generales_adjuntos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    movimiento_general_id bigint NOT NULL,
    nombre_archivo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ruta_archivo character varying(500) COLLATE pg_catalog."default" NOT NULL,
    tipo_contenido character varying(100) COLLATE pg_catalog."default",
    fecha_subida timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT pk_movimientos_generales_adjuntos PRIMARY KEY (id),
    CONSTRAINT fk_adjuntos_movimiento FOREIGN KEY (movimiento_general_id)
        REFERENCES public.movimientos_generales (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_adjuntos_movimiento 
    ON public.movimientos_generales_adjuntos (movimiento_general_id);
