-- =====================================================
-- Script SQL para Módulo: Diario Financiero
-- Base de datos: PostgreSQL
-- Fecha: 2026-05-25
-- Descripción: Registro diario de ingresos y egresos
--              con estructura cabecera-detalle, auditoría,
--              adjuntos y métodos de pago parametrizables.
-- =====================================================

-- =====================================================
-- 1. TABLAS CATÁLOGO
-- =====================================================

-- Tabla: metodos_pago (catálogo de formas de pago)
CREATE TABLE IF NOT EXISTS public.metodos_pago (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_metodos_pago PRIMARY KEY (id)
);

COMMENT ON TABLE public.metodos_pago IS 'Catálogo parametrizable de métodos de pago (efectivo, transferencia, cheque, etc.)';

-- =====================================================
-- 2. CABECERA DEL DIARIO FINANCIERO
-- =====================================================

CREATE TABLE IF NOT EXISTS public.diario_financiero_cabeceras (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fecha date NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Abierto',
    total_ingresos numeric(18, 2) NOT NULL DEFAULT 0,
    total_egresos numeric(18, 2) NOT NULL DEFAULT 0,
    saldo_dia numeric(18, 2) NOT NULL DEFAULT 0,
    observaciones text,
    creado_por character varying(100) COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    modificado_por character varying(100) COLLATE pg_catalog."default",
    fecha_modificacion timestamp without time zone,
    CONSTRAINT pk_diario_financiero_cabeceras PRIMARY KEY (id),
    CONSTRAINT uk_diario_fecha UNIQUE (fecha),
    CONSTRAINT ck_estado_valido CHECK (
        estado IN ('Abierto', 'Cerrado')
    )
);

COMMENT ON TABLE public.diario_financiero_cabeceras IS 'Cabecera del diario financiero — un registro por día con totales calculados y auditoría.';

-- =====================================================
-- 3. DETALLE (MOVIMIENTOS) DEL DIARIO FINANCIERO
-- =====================================================

CREATE TABLE IF NOT EXISTS public.diario_financiero_detalles (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cabecera_id bigint NOT NULL,
    fecha_movimiento timestamp without time zone NOT NULL,
    tipo integer NOT NULL, -- 1 = Ingreso, 2 = Egreso
    categoria_ingreso_id bigint,
    categoria_egreso_id bigint,
    numero_comprobante character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL DEFAULT '',
    monto numeric(18, 2) NOT NULL,
    metodo_pago_id bigint,
    tercero character varying(200) COLLATE pg_catalog."default",
    observaciones text,
    creado_por character varying(100) COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    modificado_por character varying(100) COLLATE pg_catalog."default",
    fecha_modificacion timestamp without time zone,
    CONSTRAINT pk_diario_financiero_detalles PRIMARY KEY (id),
    CONSTRAINT fk_detalle_cabecera FOREIGN KEY (cabecera_id) REFERENCES public.diario_financiero_cabeceras (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_categoria_ingreso FOREIGN KEY (categoria_ingreso_id) REFERENCES public.categorias_ingreso (id) ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_categoria_egreso FOREIGN KEY (categoria_egreso_id) REFERENCES public.categorias_egreso (id) ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_metodo_pago FOREIGN KEY (metodo_pago_id) REFERENCES public.metodos_pago (id) ON DELETE RESTRICT,
    CONSTRAINT ck_tipo_movimiento CHECK (tipo IN (1, 2)),
    CONSTRAINT ck_monto_positivo_df CHECK (monto > 0),
    CONSTRAINT ck_categoria_tipo_df CHECK (
        (
            tipo = 1
            AND categoria_ingreso_id IS NOT NULL
            AND categoria_egreso_id IS NULL
        )
        OR (
            tipo = 2
            AND categoria_egreso_id IS NOT NULL
            AND categoria_ingreso_id IS NULL
        )
    )
);

COMMENT ON TABLE public.diario_financiero_detalles IS 'Movimientos individuales del diario financiero (ingresos y egresos) con trazabilidad.';

-- =====================================================
-- 4. ADJUNTOS POR MOVIMIENTO
-- =====================================================

CREATE TABLE IF NOT EXISTS public.diario_financiero_adjuntos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    detalle_id bigint NOT NULL,
    nombre_archivo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ruta_archivo character varying(500) COLLATE pg_catalog."default" NOT NULL,
    tipo_contenido character varying(100) COLLATE pg_catalog."default",
    fecha_subida timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT pk_diario_financiero_adjuntos PRIMARY KEY (id),
    CONSTRAINT fk_adjunto_detalle FOREIGN KEY (detalle_id) REFERENCES public.diario_financiero_detalles (id) ON DELETE CASCADE
);

COMMENT ON TABLE public.diario_financiero_adjuntos IS 'Archivos adjuntos (facturas, recibos, comprobantes) por cada movimiento del diario.';

-- =====================================================
-- 5. ÍNDICES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_df_cabecera_fecha ON public.diario_financiero_cabeceras (fecha);

CREATE INDEX IF NOT EXISTS idx_df_cabecera_estado ON public.diario_financiero_cabeceras (estado);

CREATE INDEX IF NOT EXISTS idx_df_detalle_cabecera ON public.diario_financiero_detalles (cabecera_id);

CREATE INDEX IF NOT EXISTS idx_df_detalle_fecha ON public.diario_financiero_detalles (fecha_movimiento);

CREATE INDEX IF NOT EXISTS idx_df_detalle_tipo ON public.diario_financiero_detalles (tipo);

CREATE INDEX IF NOT EXISTS idx_df_detalle_cat_ingreso ON public.diario_financiero_detalles (categoria_ingreso_id);

CREATE INDEX IF NOT EXISTS idx_df_detalle_cat_egreso ON public.diario_financiero_detalles (categoria_egreso_id);

CREATE INDEX IF NOT EXISTS idx_df_detalle_metodo_pago ON public.diario_financiero_detalles (metodo_pago_id);

CREATE INDEX IF NOT EXISTS idx_df_adjunto_detalle ON public.diario_financiero_adjuntos (detalle_id);

-- =====================================================
-- 6. DATOS SEMILLA — MÉTODOS DE PAGO
-- =====================================================

INSERT INTO
    public.metodos_pago (nombre, activo)
VALUES ('Efectivo', true),
    (
        'Transferencia Bancaria',
        true
    ),
    ('Cheque', true),
    ('Tarjeta de Débito', true),
    ('Tarjeta de Crédito', true),
    ('Depósito Bancario', true),
    ('Otro', true)
ON CONFLICT DO NOTHING;

-- =====================================================
-- 7. FUNCIÓN: Recalcular totales de la cabecera
-- =====================================================

CREATE OR REPLACE FUNCTION public.fn_recalcular_totales_diario(p_cabecera_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_total_ingresos numeric(18,2);
    v_total_egresos  numeric(18,2);
BEGIN
    SELECT
        COALESCE(SUM(CASE WHEN tipo = 1 THEN monto ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN tipo = 2 THEN monto ELSE 0 END), 0)
    INTO v_total_ingresos, v_total_egresos
    FROM public.diario_financiero_detalles
    WHERE cabecera_id = p_cabecera_id;

    UPDATE public.diario_financiero_cabeceras
    SET total_ingresos = v_total_ingresos,
        total_egresos  = v_total_egresos,
        saldo_dia      = v_total_ingresos - v_total_egresos
    WHERE id = p_cabecera_id;
END;
$$;

COMMENT ON FUNCTION public.fn_recalcular_totales_diario (bigint) IS 'Recalcula total_ingresos, total_egresos y saldo_dia en la cabecera a partir de los detalles.';

-- =====================================================
-- 8. VERIFICACIÓN
-- =====================================================

SELECT table_name, (
        SELECT COUNT(*)
        FROM information_schema.columns c
        WHERE
            c.table_name = t.table_name
            AND c.table_schema = 'public'
    ) as columnas
FROM information_schema.tables t
WHERE
    table_schema = 'public'
    AND table_name IN (
        'metodos_pago',
        'diario_financiero_cabeceras',
        'diario_financiero_detalles',
        'diario_financiero_adjuntos'
    )
ORDER BY table_name;

SELECT 'Métodos de Pago' as catalogo, COUNT(*) as total
FROM public.metodos_pago;

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================